# https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
const
  VK_LBUTTON = 0x01
  VK_RBUTTON = 0x02
  VK_CANCEL = 0x03
  VK_MBUTTON = 0x04
  VK_BACK = 0x08
  VK_TAB = 0x09
  VK_CLEAR = 0x0C
  VK_RETURN = 0x0D
  VK_SHIFT = 0x10
  VK_CONTROL = 0x11
  VK_MENU = 0x12
  VK_PAUSE = 0x13
  VK_CAPITAL = 0x14
  VK_KANA = 0x15
  VK_HANGEUL = 0x15
  VK_HANGUL = 0x15
  VK_JUNJA = 0x17
  VK_FINAL = 0x18
  VK_HANJA = 0x19
  VK_KANJI = 0x19
  VK_ESCAPE = 0x1B
  VK_CONVERT = 0x1C
  VK_NONCONVERT = 0x1D
  VK_ACCEPT = 0x1E
  VK_MODECHANGE = 0x1F
  VK_SPACE = 0x20
  VK_PRIOR = 0x21
  VK_NEXT = 0x22
  VK_END = 0x23
  VK_HOME = 0x24
  VK_LEFT = 0x25
  VK_UP = 0x26
  VK_RIGHT = 0x27
  VK_DOWN = 0x28
  VK_SELECT = 0x29
  VK_PRINT = 0x2A
  VK_EXECUTE = 0x2B
  VK_SNAPSHOT = 0x2C
  VK_INSERT = 0x2D
  VK_DELETE = 0x2E
  VK_HELP = 0x2F
  VK_LWIN = 0x5B
  VK_RWIN = 0x5C
  VK_APPS = 0x5D
  VK_SLEEP = 0x5F
  VK_NUMPAD0 = 0x60
  VK_NUMPAD1 = 0x61
  VK_NUMPAD2 = 0x62
  VK_NUMPAD3 = 0x63
  VK_NUMPAD4 = 0x64
  VK_NUMPAD5 = 0x65
  VK_NUMPAD6 = 0x66
  VK_NUMPAD7 = 0x67
  VK_NUMPAD8 = 0x68
  VK_NUMPAD9 = 0x69
  VK_MULTIPLY = 0x6A
  VK_ADD = 0x6B
  VK_SEPARATOR = 0x6C
  VK_SUBTRACT = 0x6D
  VK_DECIMAL = 0x6E
  VK_DIVIDE = 0x6F
  VK_F1 = 0x70
  VK_F2 = 0x71
  VK_F3 = 0x72
  VK_F4 = 0x73
  VK_F5 = 0x74
  VK_F6 = 0x75
  VK_F7 = 0x76
  VK_F8 = 0x77
  VK_F9 = 0x78
  VK_F10 = 0x79
  VK_F11 = 0x7A
  VK_F12 = 0x7B
  VK_F13 = 0x7C
  VK_F14 = 0x7D
  VK_F15 = 0x7E
  VK_F16 = 0x7F
  VK_F17 = 0x80
  VK_F18 = 0x81
  VK_F19 = 0x82
  VK_F20 = 0x83
  VK_F21 = 0x84
  VK_F22 = 0x85
  VK_F23 = 0x86
  VK_F24 = 0x87
  VK_NUMLOCK = 0x90
  VK_SCROLL = 0x91
  VK_LSHIFT = 0xA0
  VK_RSHIFT = 0xA1
  VK_LCONTROL = 0xA2
  VK_RCONTROL = 0xA3
  VK_LMENU = 0xA4
  VK_RMENU = 0xA5
  VK_BROWSER_BACK = 0xA6
  VK_BROWSER_FORWARD = 0xA7
  VK_BROWSER_REFRESH = 0xA8
  VK_BROWSER_STOP = 0xA9
  VK_BROWSER_SEARCH = 0xAA
  VK_BROWSER_FAVORITES = 0xAB
  VK_BROWSER_HOME = 0xAC
  VK_VOLUME_MUTE = 0xAD
  VK_VOLUME_DOWN = 0xAE
  VK_VOLUME_UP = 0xAF
  VK_MEDIA_NEXT_TRACK = 0xB0
  VK_MEDIA_PREV_TRACK = 0xB1
  VK_MEDIA_STOP = 0xB2
  VK_MEDIA_PLAY_PAUSE = 0xB3
  VK_LAUNCH_MAIL = 0xB4
  VK_LAUNCH_MEDIA_SELECT = 0xB5
  VK_LAUNCH_APP1 = 0xB6
  VK_LAUNCH_APP2 = 0xB7
  VK_OEM_1 = 0xBA
  VK_OEM_PLUS = 0xBB
  VK_OEM_COMMA = 0xBC
  VK_OEM_MINUS = 0xBD
  VK_OEM_PERIOD = 0xBE
  VK_OEM_2 = 0xBF
  VK_OEM_3 = 0xC0
  VK_OEM_4 = 0xDB
  VK_OEM_5 = 0xDC
  VK_OEM_6 = 0xDD
  VK_OEM_7 = 0xDE
  VK_OEM_8 = 0xDF
  VK_OEM_102 = 0xE2
  VK_PROCESSKEY = 0xE5
  VK_PACKET = 0xE7
  VK_ATTN = 0xF6
  VK_CRSEL = 0xF7
  VK_EXSEL = 0xF8
  VK_EREOF = 0xF9
  VK_PLAY = 0xFA
  VK_ZOOM = 0xFB
  VK_NONAME = 0xFC
  VK_PA1 = 0xFD
  VK_OEM_CLEAR = 0xFE


type KeyCode* = distinct uint8


proc `==`*(x, y: KeyCode): bool =
  result = x.ord() == y.ord()


const
  Key_None* = KeyCode(0)
  Key_MouseLeft* = KeyCode(VK_LBUTTON)
  Key_MouseRight* = KeyCode(VK_RBUTTON)
  Key_Cancel* = KeyCode(VK_CANCEL)
  Key_MouseMiddle* = KeyCode(VK_MBUTTON)
  Key_Back* = KeyCode(VK_BACK)
  Key_Tab* = KeyCode(VK_TAB)
  Key_Clear* = KeyCode(VK_CLEAR)
  Key_Enter* = KeyCode(VK_RETURN)
  Key_Shift* = KeyCode(VK_SHIFT)
  Key_Ctrl* = KeyCode(VK_CONTROL)
  Key_Alt* = KeyCode(VK_MENU)
  Key_Pause* = KeyCode(VK_PAUSE)
  Key_Capital* = KeyCode(VK_CAPITAL)
  Key_Kana* = KeyCode(VK_KANA)
  Key_Hangeul* = KeyCode(VK_HANGEUL)
  Key_Hangul* = KeyCode(VK_HANGUL)
  Key_Junja* = KeyCode(VK_JUNJA)
  Key_Final* = KeyCode(VK_FINAL)
  Key_Hanja* = KeyCode(VK_HANJA)
  Key_Kanji* = KeyCode(VK_KANJI)
  Key_Escape* = KeyCode(VK_ESCAPE)
  Key_Esc* = KeyCode(VK_ESCAPE)
  Key_Convert* = KeyCode(VK_CONVERT)
  Key_NonConvert* = KeyCode(VK_NONCONVERT)
  Key_Accept* = KeyCode(VK_ACCEPT)
  Key_ModeChange* = KeyCode(VK_MODECHANGE)
  Key_Space* = KeyCode(VK_SPACE)
  Key_PageUp* = KeyCode(VK_PRIOR)
  Key_PageDown* = KeyCode(VK_NEXT)
  Key_End* = KeyCode(VK_END)
  Key_Home* = KeyCode(VK_HOME)
  Key_Left* = KeyCode(VK_LEFT)
  Key_Up* = KeyCode(VK_UP)
  Key_Right* = KeyCode(VK_RIGHT)
  Key_Down* = KeyCode(VK_DOWN)
  Key_Select* = KeyCode(VK_SELECT)
  Key_Print* = KeyCode(VK_PRINT)
  Key_Execute* = KeyCode(VK_EXECUTE)
  Key_Snapshot* = KeyCode(VK_SNAPSHOT)
  Key_Insert* = KeyCode(VK_INSERT)
  Key_Delete* = KeyCode(VK_DELETE)
  Key_Help* = KeyCode(VK_HELP)
  Key_LWin* = KeyCode(VK_LWIN)
  Key_RWin* = KeyCode(VK_RWIN)
  Key_Apps* = KeyCode(VK_APPS)
  Key_Sleep* = KeyCode(VK_SLEEP)
  Key_Numpad0* = KeyCode(VK_NUMPAD0)
  Key_Numpad1* = KeyCode(VK_NUMPAD1)
  Key_Numpad2* = KeyCode(VK_NUMPAD2)
  Key_Numpad3* = KeyCode(VK_NUMPAD3)
  Key_Numpad4* = KeyCode(VK_NUMPAD4)
  Key_Numpad5* = KeyCode(VK_NUMPAD5)
  Key_Numpad6* = KeyCode(VK_NUMPAD6)
  Key_Numpad7* = KeyCode(VK_NUMPAD7)
  Key_Numpad8* = KeyCode(VK_NUMPAD8)
  Key_Numpad9* = KeyCode(VK_NUMPAD9)
  Key_Multiply* = KeyCode(VK_MULTIPLY)
  Key_Add* = KeyCode(VK_ADD)
  Key_Separator* = KeyCode(VK_SEPARATOR)
  Key_Subtract* = KeyCode(VK_SUBTRACT)
  Key_Decimal* = KeyCode(VK_DECIMAL)
  Key_Divide* = KeyCode(VK_DIVIDE)
  Key_F1* = KeyCode(VK_F1)
  Key_F2* = KeyCode(VK_F2)
  Key_F3* = KeyCode(VK_F3)
  Key_F4* = KeyCode(VK_F4)
  Key_F5* = KeyCode(VK_F5)
  Key_F6* = KeyCode(VK_F6)
  Key_F7* = KeyCode(VK_F7)
  Key_F8* = KeyCode(VK_F8)
  Key_F9* = KeyCode(VK_F9)
  Key_F10* = KeyCode(VK_F10)
  Key_F11* = KeyCode(VK_F11)
  Key_F12* = KeyCode(VK_F12)
  Key_F13* = KeyCode(VK_F13)
  Key_F14* = KeyCode(VK_F14)
  Key_F15* = KeyCode(VK_F15)
  Key_F16* = KeyCode(VK_F16)
  Key_F17* = KeyCode(VK_F17)
  Key_F18* = KeyCode(VK_F18)
  Key_F19* = KeyCode(VK_F19)
  Key_F20* = KeyCode(VK_F20)
  Key_F21* = KeyCode(VK_F21)
  Key_F22* = KeyCode(VK_F22)
  Key_F23* = KeyCode(VK_F23)
  Key_F24* = KeyCode(VK_F24)
  Key_Numlock* = KeyCode(VK_NUMLOCK)
  Key_Scroll* = KeyCode(VK_SCROLL)
  Key_LShift* = KeyCode(VK_LSHIFT)
  Key_RShift* = KeyCode(VK_RSHIFT)
  Key_LCtrl* = KeyCode(VK_LCONTROL)
  Key_RCtrl* = KeyCode(VK_RCONTROL)
  Key_LAlt* = KeyCode(VK_LMENU)
  Key_RAlt* = KeyCode(VK_RMENU)
  Key_BrowserBack* = KeyCode(VK_BROWSER_BACK)
  Key_BrowserForward* = KeyCode(VK_BROWSER_FORWARD)
  Key_BrowserRefresh* = KeyCode(VK_BROWSER_REFRESH)
  Key_BrowserStop* = KeyCode(VK_BROWSER_STOP)
  Key_BrowserSearch* = KeyCode(VK_BROWSER_SEARCH)
  Key_BrowserFavorites* = KeyCode(VK_BROWSER_FAVORITES)
  Key_BrowserHome* = KeyCode(VK_BROWSER_HOME)
  Key_VolumeMute* = KeyCode(VK_VOLUME_MUTE)
  Key_VolumeDown* = KeyCode(VK_VOLUME_DOWN)
  Key_VolumeUp* = KeyCode(VK_VOLUME_UP)
  Key_MediaNextTrack* = KeyCode(VK_MEDIA_NEXT_TRACK)
  Key_MediaPrevTrack* = KeyCode(VK_MEDIA_PREV_TRACK)
  Key_MediaStop* = KeyCode(VK_MEDIA_STOP)
  Key_MediaPlayPause* = KeyCode(VK_MEDIA_PLAY_PAUSE)
  Key_LaunchMail* = KeyCode(VK_LAUNCH_MAIL)
  Key_LaunchMediaSelect* = KeyCode(VK_LAUNCH_MEDIA_SELECT)
  Key_LaunchApp1* = KeyCode(VK_LAUNCH_APP1)
  Key_LaunchApp2* = KeyCode(VK_LAUNCH_APP2)
  Key_Oem1* = KeyCode(VK_OEM_1)
  Key_OemPlus* = KeyCode(VK_OEM_PLUS)
  Key_OemComma* = KeyCode(VK_OEM_COMMA)
  Key_OemMinus* = KeyCode(VK_OEM_MINUS)
  Key_OemPeriod* = KeyCode(VK_OEM_PERIOD)
  Key_Oem2* = KeyCode(VK_OEM_2)
  Key_Oem3* = KeyCode(VK_OEM_3)
  Key_Oem4* = KeyCode(VK_OEM_4)
  Key_Oem5* = KeyCode(VK_OEM_5)
  Key_Oem6* = KeyCode(VK_OEM_6)
  Key_Oem7* = KeyCode(VK_OEM_7)
  Key_Oem8* = KeyCode(VK_OEM_8)
  Key_Oem102* = KeyCode(VK_OEM_102)
  Key_ProcessKey* = KeyCode(VK_PROCESSKEY)
  Key_Packet* = KeyCode(VK_PACKET)
  Key_Attn* = KeyCode(VK_ATTN)
  Key_Crsel* = KeyCode(VK_CRSEL)
  Key_Exsel* = KeyCode(VK_EXSEL)
  Key_Ereof* = KeyCode(VK_EREOF)
  Key_Play* = KeyCode(VK_PLAY)
  Key_Zoom* = KeyCode(VK_ZOOM)
  Key_Noname* = KeyCode(VK_NONAME)
  Key_Pa1* = KeyCode(VK_PA1)
  Key_OemClear* = KeyCode(VK_OEM_CLEAR)
  Key_A* = KeyCode(ord 'A')
  Key_B* = KeyCode(ord 'B')
  Key_C* = KeyCode(ord 'C')
  Key_D* = KeyCode(ord 'D')
  Key_E* = KeyCode(ord 'E')
  Key_F* = KeyCode(ord 'F')
  Key_G* = KeyCode(ord 'G')
  Key_H* = KeyCode(ord 'H')
  Key_I* = KeyCode(ord 'I')
  Key_J* = KeyCode(ord 'J')
  Key_K* = KeyCode(ord 'K')
  Key_L* = KeyCode(ord 'L')
  Key_M* = KeyCode(ord 'M')
  Key_N* = KeyCode(ord 'N')
  Key_O* = KeyCode(ord 'O')
  Key_P* = KeyCode(ord 'P')
  Key_Q* = KeyCode(ord 'Q')
  Key_R* = KeyCode(ord 'R')
  Key_S* = KeyCode(ord 'S')
  Key_T* = KeyCode(ord 'T')
  Key_U* = KeyCode(ord 'U')
  Key_V* = KeyCode(ord 'V')
  Key_W* = KeyCode(ord 'W')
  Key_X* = KeyCode(ord 'X')
  Key_Y* = KeyCode(ord 'Y')
  Key_Z* = KeyCode(ord 'Z')
  Key_0* = KeyCode(ord '0')
  Key_1* = KeyCode(ord '1')
  Key_2* = KeyCode(ord '2')
  Key_3* = KeyCode(ord '3')
  Key_4* = KeyCode(ord '4')
  Key_5* = KeyCode(ord '5')
  Key_6* = KeyCode(ord '6')
  Key_7* = KeyCode(ord '7')
  Key_8* = KeyCode(ord '8')
  Key_9* = KeyCode(ord '9')


var keyNames: array[256, string]
keyNames[Key_None.ord()] = "None"
keyNames[Key_MouseLeft.ord()] = "Mouse Left"
keyNames[Key_MouseRight.ord()] = "Mouse Right"
keyNames[Key_Cancel.ord()] = "Cancel"
keyNames[Key_MouseMiddle.ord()] = "Mouse Middle"
keyNames[Key_Back.ord()] = "Back"
keyNames[Key_Tab.ord()] = "Tab"
keyNames[Key_Clear.ord()] = "Clear"
keyNames[Key_Enter.ord()] = "Enter"
keyNames[Key_Shift.ord()] = "Shift"
keyNames[Key_Ctrl.ord()] = "Ctrl"
keyNames[Key_Alt.ord()] = "Alt"
keyNames[Key_Pause.ord()] = "Pause"
keyNames[Key_Capital.ord()] = "Capital"
keyNames[Key_Kana.ord()] = "Kana"
keyNames[Key_Hangeul.ord()] = "Hangeul"
keyNames[Key_Hangul.ord()] = "Hangul"
keyNames[Key_Junja.ord()] = "Junja"
keyNames[Key_Final.ord()] = "Final"
keyNames[Key_Hanja.ord()] = "Hanja"
keyNames[Key_Kanji.ord()] = "Kanji"
keyNames[Key_Escape.ord()] = "Escape"
keyNames[Key_Convert.ord()] = "IME convert"
keyNames[Key_NonConvert.ord()] = "IME nonconvert"
keyNames[Key_Accept.ord()] = "IME accept"
keyNames[Key_ModeChange.ord()] = "IME mode change"
keyNames[Key_Space.ord()] = "Space"
keyNames[Key_PageUp.ord()] = "Page Up"
keyNames[Key_PageDown.ord()] = "Page Down"
keyNames[Key_End.ord()] = "End"
keyNames[Key_Home.ord()] = "Home"
keyNames[Key_Left.ord()] = "Arrow Left"
keyNames[Key_Up.ord()] = "Arrow Up"
keyNames[Key_Right.ord()] = "Arrow Right"
keyNames[Key_Down.ord()] = "Arrow Down"
keyNames[Key_Select.ord()] = "Select"
keyNames[Key_Print.ord()] = "Print"
keyNames[Key_Execute.ord()] = "Execute"
keyNames[Key_Snapshot.ord()] = "Print Screen"
keyNames[Key_Insert.ord()] = "Insert"
keyNames[Key_Delete.ord()] = "Delete"
keyNames[Key_Help.ord()] = "Help"
keyNames[Key_LWin.ord()] = "Win Left"
keyNames[Key_RWin.ord()] = "Win Right"
keyNames[Key_Apps.ord()] = "Applications"
keyNames[Key_Sleep.ord()] = "Sleep"
keyNames[Key_Numpad0.ord()] = "Numpad 0"
keyNames[Key_Numpad1.ord()] = "Numpad 1"
keyNames[Key_Numpad2.ord()] = "Numpad 2"
keyNames[Key_Numpad3.ord()] = "Numpad 3"
keyNames[Key_Numpad4.ord()] = "Numpad 4"
keyNames[Key_Numpad5.ord()] = "Numpad 5"
keyNames[Key_Numpad6.ord()] = "Numpad 6"
keyNames[Key_Numpad7.ord()] = "Numpad 7"
keyNames[Key_Numpad8.ord()] = "Numpad 8"
keyNames[Key_Numpad9.ord()] = "Numpad 9"
keyNames[Key_Multiply.ord()] = "Multiply"
keyNames[Key_Add.ord()] = "Add"
keyNames[Key_Separator.ord()] = "Separator"
keyNames[Key_Subtract.ord()] = "Subtract"
keyNames[Key_Decimal.ord()] = "Decimal"
keyNames[Key_Divide.ord()] = "Divide"
keyNames[Key_F1.ord()] = "F1"
keyNames[Key_F2.ord()] = "F2"
keyNames[Key_F3.ord()] = "F3"
keyNames[Key_F4.ord()] = "F4"
keyNames[Key_F5.ord()] = "F5"
keyNames[Key_F6.ord()] = "F6"
keyNames[Key_F7.ord()] = "F7"
keyNames[Key_F8.ord()] = "F8"
keyNames[Key_F9.ord()] = "F9"
keyNames[Key_F10.ord()] = "F10"
keyNames[Key_F11.ord()] = "F11"
keyNames[Key_F12.ord()] = "F12"
keyNames[Key_F13.ord()] = "F13"
keyNames[Key_F14.ord()] = "F14"
keyNames[Key_F15.ord()] = "F15"
keyNames[Key_F16.ord()] = "F16"
keyNames[Key_F17.ord()] = "F17"
keyNames[Key_F18.ord()] = "F18"
keyNames[Key_F19.ord()] = "F19"
keyNames[Key_F20.ord()] = "F20"
keyNames[Key_F21.ord()] = "F21"
keyNames[Key_F22.ord()] = "F22"
keyNames[Key_F23.ord()] = "F23"
keyNames[Key_F24.ord()] = "F24"
keyNames[Key_Numlock.ord()] = "Num Lock"
keyNames[Key_Scroll.ord()] = "Scroll Lock"
keyNames[Key_LShift.ord()] = "Shift Left"
keyNames[Key_RShift.ord()] = "Shift Right"
keyNames[Key_LCtrl.ord()] = "Ctrl Left"
keyNames[Key_RCtrl.ord()] = "Ctrl Right"
keyNames[Key_LAlt.ord()] = "Alt Left"
keyNames[Key_RAlt.ord()] = "Alt Right"
keyNames[Key_BrowserBack.ord()] = "Browser Back"
keyNames[Key_BrowserForward.ord()] = "Browser Forward"
keyNames[Key_BrowserRefresh.ord()] = "Browser Refresh"
keyNames[Key_BrowserStop.ord()] = "Browser Stop"
keyNames[Key_BrowserSearch.ord()] = "Browser Search"
keyNames[Key_BrowserFavorites.ord()] = "Browser Favorites"
keyNames[Key_BrowserHome.ord()] = "Browser Home"
keyNames[Key_VolumeMute.ord()] = "Volume Mute"
keyNames[Key_VolumeDown.ord()] = "Volume Down"
keyNames[Key_VolumeUp.ord()] = "Volume Up"
keyNames[Key_MediaNextTrack.ord()] = "Next Track"
keyNames[Key_MediaPrevTrack.ord()] = "Prev Track"
keyNames[Key_MediaStop.ord()] = "Stop Media"
keyNames[Key_MediaPlayPause.ord()] = "Play/Pause Media"
keyNames[Key_LaunchMail.ord()] = "Start Mail"
keyNames[Key_LaunchMediaSelect.ord()] = "Select Media"
keyNames[Key_LaunchApp1.ord()] = "Start Application 1"
keyNames[Key_LaunchApp2.ord()] = "Start Application 2"
keyNames[Key_Oem1.ord()] = "OEM 1 (;)"
keyNames[Key_OemPlus.ord()] = "+"
keyNames[Key_OemComma.ord()] = ","
keyNames[Key_OemMinus.ord()] = "-"
keyNames[Key_OemPeriod.ord()] = "."
keyNames[Key_Oem2.ord()] = "OEM 2 (/)"
keyNames[Key_Oem3.ord()] = "OEM 3 (~)"
keyNames[Key_Oem4.ord()] = "OEM 4 ([)"
keyNames[Key_Oem5.ord()] = "OEM 5 (\\)"
keyNames[Key_Oem6.ord()] = "OEM 6 (])"
keyNames[Key_Oem7.ord()] = "OEM 7 (')"
keyNames[Key_Oem8.ord()] = "OEM 8"
keyNames[Key_Oem102.ord()] = "OEM 102 (<)"
keyNames[Key_ProcessKey.ord()] = "IME PROCESS key"
keyNames[Key_Packet.ord()] = "VK_PACKET"
keyNames[Key_Attn.ord()] = "Attn"
keyNames[Key_Crsel.ord()] = "CrSel"
keyNames[Key_Exsel.ord()] = "ExSel"
keyNames[Key_Ereof.ord()] = "Erase EOF"
keyNames[Key_Play.ord()] = "Play"
keyNames[Key_Zoom.ord()] = "Zoom"
keyNames[Key_Noname.ord()] = "Noname"
keyNames[Key_Pa1.ord()] = "PA1"
keyNames[Key_OemClear.ord()] = "Clear"
keyNames[Key_A.ord()] = "A"
keyNames[Key_B.ord()] = "B"
keyNames[Key_C.ord()] = "C"
keyNames[Key_D.ord()] = "D"
keyNames[Key_E.ord()] = "E"
keyNames[Key_F.ord()] = "F"
keyNames[Key_G.ord()] = "G"
keyNames[Key_H.ord()] = "H"
keyNames[Key_I.ord()] = "I"
keyNames[Key_J.ord()] = "J"
keyNames[Key_K.ord()] = "K"
keyNames[Key_L.ord()] = "L"
keyNames[Key_M.ord()] = "M"
keyNames[Key_N.ord()] = "N"
keyNames[Key_O.ord()] = "O"
keyNames[Key_P.ord()] = "P"
keyNames[Key_Q.ord()] = "Q"
keyNames[Key_R.ord()] = "R"
keyNames[Key_S.ord()] = "S"
keyNames[Key_T.ord()] = "T"
keyNames[Key_U.ord()] = "U"
keyNames[Key_V.ord()] = "V"
keyNames[Key_W.ord()] = "W"
keyNames[Key_X.ord()] = "X"
keyNames[Key_Y.ord()] = "Y"
keyNames[Key_Z.ord()] = "Z"
keyNames[Key_0.ord()] = "0"
keyNames[Key_1.ord()] = "1"
keyNames[Key_2.ord()] = "2"
keyNames[Key_3.ord()] = "3"
keyNames[Key_4.ord()] = "4"
keyNames[Key_5.ord()] = "5"
keyNames[Key_6.ord()] = "6"
keyNames[Key_7.ord()] = "7"
keyNames[Key_8.ord()] = "8"
keyNames[Key_9.ord()] = "9"


proc `$`*(keyCode: KeyCode): string =
  result = keyNames[keyCode.ord()]
  if result == "":
    result = "KeyCode " & $keyCode.ord()
